sudo: true
dist: trusty
cache: false
group: deprecated-2017Q2
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- echo %ANT_HOME%
script:
- ant git-diff-deploy